# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NeuroBox3D
email: info@neurobox.eu
description: "
	Bringing together numerical mathematics, scientific and 
	high performance computing and life sciences
	"
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://neurobox.eu" # the base hostname & protocol for your site
url: ""
twitter_username: neurobox3d
github_username:  neurobox3d

# Build settings
markdown: kramdown
